# font size, measured in points
[font]
    size = 12.5

[font.normal]
    family = "VCROSDMonoNerdFont"

# Offset is the extra space around each character
# y: line spacing
# x: character spacing
[font.offset]
    x = 1
    y = 2
